name: Build main branch and upload dependency graph

on:
  push:
    branches: [ main ]

# Cancel previous jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  upload-dependency-graph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: ./.github/actions/maven-build
      with:
        build-command: install org.sonatype.central:central-publishing-maven-plugin:0.7.0:publish -P release # Deploy a snapshot build of main
      env:
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        GPG_PRIVATE_KEY: ${{ secrets.RUNE_GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.RUNE_GPG_PASSPHRASE }}
    # Upload full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v5
